[build]
  command = "npm run build"
  publish = "dist/client"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "22.17.0"

[context.production.environment]
  NODE_ENV = "production"
