# This is the main build configuration for your site.
[build]
  # command: This tells Netlify to run the "build" script 
  # from your package.json file. For your project, this
  # command is "vite build".
  command = "npm run build"

  # publish: After the command runs, Vite places all the
  # optimized, final website files (HTML, CSS, JS) into a 
  # directory named "dist". This tells Netlify to deploy 
  # the contents of that "dist" folder.
  publish = "dist"

  # functions: This tells Netlify where to find your
  # serverless function so it can be deployed correctly.
  functions = "netlify/functions"
